# Default configuration - Use setup scripts for best experience
# Windows: run setup.bat
# macOS: run ./setup.sh

version: '3.8'
services:
  frontend:
    image: nginx:alpine
    container_name: asl-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    networks:
      - asl-net
  sign-language-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: asl-backend
    volumes:
      - ./backend/models:/app/backend/models
      - ./backend/training_data:/app/backend/training_data
      - ./backend/app:/app/backend/app
    environment:
      - DISPLAY=host.docker.internal:0
      - CAMERA_INDEX=0
      - PLATFORM=default
    ports:
      - "5001:5001"
    network_mode: bridge
    stdin_open: true
    tty: true
networks:
  asl-net:
    driver: bridge