# Default configuration - Use setup scripts for best experience
# Windows: run setup.bat
# macOS: run ./setup.sh

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asl-frontend
    ports:
      - "3000:80"
    networks:
      - asl-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asl-backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_RELOAD=true
    tty: true
    networks:
      - asl-net

networks:
  asl-net:
    driver: bridge